Update to use rollkit cli instead of <binary>d
rollkit/docs pull request #383
Opened 2024-05-21 23:41 UTC by yarikbratashchuk

## Overview

2024-05-23 18:03 UTC, MSevey commented
> The version of the rollkit cli should be different after [rollkit/rollkit#1680](https://github.com/rollkit/rollkit/pull/1680) is merged

Does this work prior to 1680 being merged? 
If not, let's mark this as draft and update it once 1680 is merged, otherwise I would imagine this would break the docs.

2024-05-24 13:29 UTC, MSevey requested changes
pending answer to previous question

2024-06-07 15:59 UTC, Manav-Aggarwal reviewed
@yarikbratashchuk to resolve this once ready to merge

2024-06-08 22:53 UTC, Manav-Aggarwal commented on .vitepress/config.ts
>            items: [
Resolve once ready to merge @yarikbratashchuk

2024-06-12 17:13 UTC, Manav-Aggarwal commented
Cannot see the preview: https://github.com/rollkit/docs/actions/runs/9486810092/job/26142007535?pr=383, please fix before making ready for review

2024-06-14 13:19 UTC, MSevey commented on guides/use-rollkit-cli
does this need th `.md` file extension?

2024-06-14 13:22 UTC, MSevey commented
The preview doesn't seem to have updated. Did you verify this built locally?

2024-06-14 13:55 UTC, jcstein commented on guides/use-rollkit-cli
yes

2024-06-14 13:57 UTC, jcstein commented on guides/connect-local-da.md
> +# How to Connect a Rollup to a Local DA Network
```suggestion
# How to connect a rollup to a local DA network
```

2024-06-14 13:57 UTC, jcstein commented on .vitepress/config.ts
> +              text: "Connect to a Local DA",
```suggestion
              text: "Connect to a local DA",
```

2024-06-14 13:57 UTC, jcstein commented on guides/connect-local-da.md
> +## Setting Up a Local DA Network
```suggestion
## Setting up a local DA network
```

2024-06-14 13:58 UTC, jcstein commented on guides/connect-local-da.md
> +## Configuring Your Rollup to Connect to the Local DA Network
```suggestion
## Configuring your rollup to connect to the local DA network
```

2024-06-14 13:58 UTC, jcstein commented on guides/connect-local-da.md
> +## Run Your Rollup
```suggestion
## Run your rollup
```

2024-06-14 13:58 UTC, jcstein commented on guides/create-genesis.md
> +# How to Create a Genesis for Your Rollup
```suggestion
# How to create a genesis for your rollup
```

2024-06-14 13:58 UTC, jcstein commented on guides/create-genesis.md
> +# How to Create a Genesis for Your Rollup
"genesis file"?

2024-06-14 13:58 UTC, jcstein commented on guides/create-genesis.md
> +## 1. Setting Variables
```suggestion
## 1. Setting variables
```

2024-06-14 13:58 UTC, jcstein commented on guides/create-genesis.md
> +## 2. Ensuring `rollkit.toml` is Present and Building Entrypoint
```suggestion
## 2. Ensuring `rollkit.toml` is present and building entrypoint
```

2024-06-14 13:59 UTC, jcstein commented on guides/create-genesis.md
> +## 3. Resetting Existing Genesis/Chain Data
```suggestion
## 3. Resetting existing genesis/chain data
```

2024-06-14 13:59 UTC, jcstein commented on guides/create-genesis.md
> +## 4. Initializing the Validator
```suggestion
## 4. Initializing the validator
```

2024-06-14 13:59 UTC, jcstein commented on guides/create-genesis.md
> +## 5. Adding a Key to Keyring Backend
```suggestion
## 5. Adding a key to keyring backend
```

2024-06-14 13:59 UTC, jcstein commented on guides/create-genesis.md
> +## 6. Adding a Genesis Account
```suggestion
## 6. Adding a genesis account
```

2024-06-14 13:59 UTC, jcstein commented on guides/create-genesis.md
> +## 7. Setting the Staking Amount in the Genesis Transaction
```suggestion
## 7. Setting the staking amount in the genesis transaction
```

2024-06-14 13:59 UTC, jcstein commented on guides/create-genesis.md
> +## 8. Collecting Genesis Transactions
```suggestion
## 8. Collecting genesis transactions
```

2024-06-14 13:59 UTC, jcstein commented on guides/create-genesis.md
> +## 9. Configuring the Genesis File
```suggestion
## 9. Configuring the genesis file
```

2024-06-14 14:00 UTC, jcstein commented on guides/create-genesis.md
> +## 10. Creating a Restart Script
```suggestion
## 10. Creating a restart script
```

2024-06-14 14:00 UTC, jcstein commented on guides/create-genesis.md
> +## 11. Starting the Chain
```suggestion
## 11. Starting the chain
```

2024-06-14 14:00 UTC, jcstein commented on guides/max-pending-blocks.md
> +
```suggestion
```

2024-06-14 14:01 UTC, jcstein commented on guides/use-rollkit-cli
> +# How to Use Rollkit CLI
```suggestion
# How to use Rollkit CLI
```

2024-06-14 14:01 UTC, jcstein commented on guides/use-rollkit-cli
> +### Steps to Generate `rollkit.toml`:
```suggestion
### Steps to generate `rollkit.toml`:
```

2024-06-14 14:01 UTC, jcstein commented on guides/use-rollkit-cli
> +## 3. Running Rollup Commands Using Rollkit CLI
```suggestion
## 3. Running rollup commands using Rollkit CLI
```

2024-06-14 14:01 UTC, jcstein commented on tutorials/celestia-da.md
> +# Deploying rollup to Celestia
```suggestion
# Deploying a rollup to Celestia  
```

2024-06-14 14:02 UTC, jcstein commented on tutorials/celestia-da.md
> +## 🏗️ Building Your Sovereign Rollup {#building-your-sovereign-rollup}
```suggestion
## 🏗️ Building your sovereign rollup {#building-your-sovereign-rollup}
```

2024-06-14 14:02 UTC, jcstein commented on tutorials/celestia-da.md
> +## 🧰 Configuring Your Rollup {#configuring-your-rollup}
```suggestion
## 🧰 Configuring your rollup {#configuring-your-rollup}
```

2024-06-14 14:02 UTC, jcstein commented on tutorials/gm-world.md
>  ## 🌐 Running a Local DA Network {#running-local-da}
```suggestion
## 🌐 Running a local DA network {#running-local-da}
```

2024-06-14 14:03 UTC, jcstein commented on tutorials/gm-world.md
> +## 🧰 Configuring Your Rollup {#configuring-your-rollup}
```suggestion
## 🧰 Configuring your rollup {#configuring-your-rollup}
```

2024-06-14 14:04 UTC, jcstein requested changes
first pass, mostly suggestions for sentence case in titles, instead of title case. needs to be applied, then I will review all of the copy more carefully.

2024-06-14 14:07 UTC, yarikbratashchuk commented on guides/use-rollkit-cli
agh
yeah

2024-06-14 14:50 UTC, yarikbratashchuk commented
> The preview doesn't seem to have updated. Did you verify this built locally?

Yes I did, something's off

2024-06-14 15:51 UTC, closed without merging

2024-06-14 16:04 UTC, jcstein commented
:pepehands: